# Generated by Django 2.0.3 on 2018-03-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testcases.TestCase')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distroName', models.CharField(max_length=128)),
                ('setup', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='testRun',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testruns.TestRun'),
        ),
    ]
