# Generated by Django 2.0.3 on 2018-03-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('params', models.CharField(max_length=512)),
                ('hostRequires', models.CharField(max_length=512)),
                ('component', models.CharField(max_length=128)),
                ('testType', models.CharField(max_length=64)),
                ('archIn', models.CharField(max_length=128)),
                ('archNotIn', models.CharField(max_length=128)),
                ('distroIn', models.CharField(max_length=128)),
                ('distroNotIn', models.CharField(max_length=128)),
            ],
        ),
    ]
